version: '3.8'

services:
    backend-api:
        image: localhost/intserv-2020/backend:latest
        build:
            context: ./backend
        volumes:
            - backend-data:/data:rw,z
        ports: 
            - 2000:2000

volumes:
    backend-data: {}
